spring:
    application:
        name: cloud
    datasource:
        url: jdbc:mysql://localhost:3306/xmass?serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    webflux:
        session:
            timeout: 30m # ?? ???? ??
    reactor:
        netty:
            request-timeout: 5000ms # ?? ???? ?? (5?)

api:
    header: KakaoAK
    directions: https://apis-navi.kakaomobility.com/v1/directions

server:
    reactive:
        netty:
            max-chunk-size: 16KB # ?? ?? ?? ??
            max-initial-line-length: 16KB # ??? ? ?? ?? ?? ?? ??
            max-header-size: 16KB # HTTP ?? ?? ??
            max-in-memory-size: 16MB # ?? ?? ??? ??? ? ?? ?? ??
    http2:
        enabled: true # HTTP/2 ???
    codec:
        max-in-memory-size: 16MB # HTTP ??/???? ???? ???? ???? ?? ??
reactor:
    netty:
        pool:
            max-connections: 200 # ?? ?? ? ??
            acquire-timeout: 45000 # ?? ?? ?? ?? (45?)
logging:
    level:
        org.springframework.web.reactive.function.client: DEBUG
    config: classpath:log4j2/log4j2-local.xml

management:
    endpoints:
        web:
            exposure:
                include: health, metrics, httptrace