spring:
    application:
        name: cloud
    datasource:
        url: jdbc:mysql://localhost:3306/xmass?serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

api:
    header: KakaoAK
    directions: https://apis-navi.kakaomobility.com/v1/directions
