application:
    target: SHIB

spring:
    application:
        name: cloud
    datasource:
        url: jdbc:mysql://localhost:3306/xmass?serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    webflux:
        session:
            timeout: 30m # ?? ???? ??
    reactor:
        netty:
            request-timeout: 5000ms # ?? ???? ?? (5?)
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: trading-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.DoubleSerializer

api:
    url: https://api.upbit.com

server:
    tomcat:
        mbeanregistry:
            enabled: true
    reactive:
        netty:
            max-chunk-size: 16KB # ?? ?? ?? ??
            max-initial-line-length: 16KB # ??? ? ?? ?? ?? ?? ??
            max-header-size: 16KB # HTTP ?? ?? ??
            max-in-memory-size: 16MB # ?? ?? ??? ??? ? ?? ?? ??
    http2:
        enabled: true # HTTP/2 ???
    codec:
        max-in-memory-size: 16MB # HTTP ??/???? ???? ???? ???? ?? ??
reactor:
    netty:
        pool:
            max-connections: 200 # ?? ?? ? ??
            acquire-timeout: 45000 # ?? ?? ?? ?? (45?)
logging:
    level:
        com.xmass.cloud.web.controller: DEBUG
        org.springframework.web.reactive.function.client: DEBUG
    config: classpath:log4j2/log4j2-local.xml

management:
    server:
        port: 9090
    info:
        java:
            enabled: true
        os:
            enabled: true
        env:
            enabled: true
        git:
            enabled: true
    endpoint:
        health:
            show-details: always
        #            show-components: always
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
                exclude: "env,beans"
            base-path: "/manage"
info:
    app:
        name: hello-actuator
        company: dh


